spring:
  datasource:
    url: jdbc:mysql://8.144.160.27:3306/db_sf_config?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
    username: root
    password: lxA_Pu%oS8Pl