spring:
  application:
    name: fl-discovery
  profiles:
    active: dev
server:
  port: 8761
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS